## NumPy Basics

In [8]:
!pip3 install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 34.1 MB/s  0:00:00

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip


In [9]:
!pip3 install --upgrade pip

  Using cached pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-26.0.1-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 25.3
    Uninstalling pip-25.3:
      Successfully uninstalled pip-25.3


In [10]:
import numpy as np

# Create array from list

arr = np.array([1, 2, 3, 4, 5])
print(arr)       # [1 2 3 4 5]

[1 2 3 4 5]


In [11]:
# Mathematical operations (vectorized!)

print(arr * 2)   # [ 2  4  6  8 10]
print(arr + 10)  # [11 12 13 14 15]
print(arr ** 2)  # [ 1  4  9 16 25]

[ 2  4  6  8 10]
[11 12 13 14 15]
[ 1  4  9 16 25]


In [12]:
# Works on ALL elements at once!
# Much faster than loops
# 2D array (matrix)

In [13]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]
